apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: onlineeventbookingzakariyaabbas
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: onlineeventbookingzakariyaabbas
  labels:
    app: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: zakariyaabbas/notification-service:latest
          ports:
            - containerPort: 6000
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_HOST

            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_PORT

            - name: RABBITMQ_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBITMQ_QUEUE

            - name: FROM_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FROM_EMAIL

            - name: SMTP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SMTP_SERVER

            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SMTP_PORT

            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_PASSWORD
